# Generated by Django 2.2.12 on 2021-09-08 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210907_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='answers',
            name='option',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='testapp.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=1000),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz',
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ManyToManyField(related_name='question_set', to='testapp.Quiz'),
        ),
    ]
